apiVersion: v1
kind: Service
metadata:
  name: poc-demo-app
  labels:
    app: poc-demo-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: poc-demo-app
