apiVersion: batch/v1
kind: CronJob
metadata:
  name: poc-postgres-backup
spec:
  schedule: "0 2 * * *"  # Run at 2 AM daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: bitnami/postgresql:16
              command:
                - /bin/bash
                - -c
                - |
                  echo "Starting backup at $(date)"
                  PGPASSWORD=$DB_PASSWORD pg_dump -h poc-postgres-postgresql -U pocapp -d pocdb > /backup/backup-$(date +%Y%m%d-%H%M%S).sql
                  echo "Backup completed at $(date)"
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: poc-db-credentials
                      key: password
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          volumes:
            - name: backup-storage
              emptyDir: {}  # In real scenario, use PVC
