apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lhw-openproject-postgres-backup
  labels:
    app: lhw-openproject-postgres-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G 
